[package]
name = "shape"
version = "0.1.1"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
geo = "0.28.0"
dbase = "0.5.0"
wkt = "0.10.3"
csv = "1.3.0"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"
